
if(WIN32) 
    set(STRAITX_PLATFORM_WINDOWS 1)
    message("Windows")
elseif(MINGW)
    message(FATAL_ERROR "MinGW is not supported yet.")
elseif(APPLE)
    if(IOS)
        set(STRAITX_PLATFORM_IOS 1)
        message(FATAL_ERROR "IOS is not supported yet.")
    else()
        set(STRAITX_PLATFORM_MACOS 1)
        message("MacOS")
    endif()
elseif(UNIX)
    # we dont have a linux cmake variable so this is the only option available
    if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
        set(STRAITX_PLATFORM_LINUX 1)
        message("Linux")
    elseif(ANDROID)
        set(STRATIX_PLATFORM_ANDROID 1)
        message(FATAL_ERROR "Android is not supported yet.")
    else()
        message(FATAL_ERROR "This Unix-based operating system is not supported yet.")
    endif()
else()
    message(FATAL_ERROR "Your operating system is not supported yet.")
endif()

if(STRAITX_PLATFORM_WINDOWS)
	set(STRAITX_SUPPORT_OPENGL 1)
	set(STRAITX_SUPPORT_VULKAN 1)
elseif(STRAITX_PLATFORM_LINUX)
	set(STRAITX_SUPPORT_OPENGL 1)
	set(STRAITX_SUPPORT_VULKAN 1)
elseif(STRAITX_PLATFORM_MACOS)
	set(STRAITX_SUPPORT_OPENGL 1)
	set(STRAITX_SUPPORT_VULKAN 1)
else()
    message(FATAL_ERROR "Your platform does not support any graphics api yet.")
endif()